name: Move major tag
# Automatically move the major tag vX when vX.Y.Z is created

on:
  push:
    tags:
    - v*

jobs:
  autotag-major:
#    if: github.event.base_ref=='refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Get repo HEAD ref
      uses: actions/github-script@v5
      with:
        script: |
          
          const parsed = context.ref.match(/^refs\/tags\/(?<minor>(?<major>v\d+)\.\d+)\.\d+$/) 
          if (!parsed) {
            console.log(`Ignoring tag ${context.ref} - not a semver release tag.`);
            return;
          }
          
          const response = await github.rest.git.getRef({ 
            ref: `heads/${context.payload.repository.default_branch}`, 
            owner: context.repo.owner, 
            repo: context.repo.repo 
          });
          
          console.log(response);
          
          const repoHeadSha = response.data.sha;
          
          if (repoHeadSha !== context.sha) {
            console.log(`Ignoring tag at ${context.sha}, because repo HEAD is at ${repoHeadSha}.`);
            return;
          }
          
          core.setOutput('major', parsed.groups.major);
          core.setOutput('minor', parsed.groups.minor);

      id: new-tag

    - run: "echo ${{ steps.new-tag.outputs.major }}"
      if: ${{ steps.new-tag.outputs.major }}
