name: Move major tag
# Automatically move the major tag vX when vX.Y.Z is created

on:
  push:
    tags:
    - v*

jobs:
  autotag-major:
#    if: github.event.base_ref=='refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - run: "echo '${{ github.event.after }}'"
    - name: Get repo HEAD ref
      uses: actions/github-script@v5
      with:
        script: |
          console.log(await github.git.getRef({
            owner: context.repo.owner,
            ref: "heads/main",
            repo: context.repo.repo,
          }));
