name: Node.js CI

on:
  schedule:
  - cron:  '23 4 * * *' # Once, nightly
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    uses: dominykas/test-things/.github/workflows/test.yaml@main
    with:
      upgradePolicy: lts
