on:
  workflow_call:
    inputs:
      upgradePolicy:
        description: "Node.js version upgrade policy. Allowed values: `lts` (default), `lts/strict`, `all`."
        default: lts
        required: false
        type: string

jobs:

  prepare-node-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - uses: actions/checkout@v2
    - uses: dominykas/test-things/actions/prepare-matrix@main
      id: set-matrix
      with:
        upgrade-policy: ${{ upgrade-policy }}

  test:
    runs-on: ubuntu-latest
    needs: prepare-node-matrix

    strategy:
      matrix:
        node-version: ${{ fromJson(needs.prepare-node-matrix.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run tests-only
