on:
  workflow_call:
    inputs:
      upgrade-policy:
        description: 'Node.js version upgrade policy. Allowed values: `lts` (default), `lts/strict`, `all`.'
        default: 'lts'
        required: false
        type: string

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 14, 12 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run tests-only

  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run lint
