name: Check comment actor

on:
  pull_request:

jobs:
  print_actor:
    name: Print actor
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -X GET --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}' 'https://api.github.com/user'
